version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - django_ledger_network
    restart: unless-stopped

  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: osm_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: OWEN
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - django_ledger_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d osm_data"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  django_ledger_network:
    driver: bridge
