version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    networks:
      - django_ledger_network
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:

networks:
  django_ledger_network:
    driver: bridge
