# Generated by Django 5.1.7 on 2025-04-01 11:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Road",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
            ],
        ),
    ]
