# Generated by Django 5.1.7 on 2025-04-01 19:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0003_osmpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="BufferedRoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
