# Generated by Django 5.1.7 on 2025-04-02 07:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0004_bufferedroad"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanetOSMPolygon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osm_id", models.BigIntegerField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("way", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
