# Generated by Django 5.1.7 on 2025-04-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0005_planetosmpolygon"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedRoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osm_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("geometry", models.JSONField()),
            ],
        ),
    ]
