# Generated by Django 5.1.7 on 2025-04-12 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0008_cachedbuildings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CachedBuildings",
            new_name="DITCachedBuildings",
        ),
    ]
