# Generated by Django 5.1.7 on 2025-04-12 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0011_ditcachedbuildings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DITCachedBuildings",
        ),
    ]
